#!/usr/bin/env ruby
require 'io/console'
require_relative 'boggle_cli'

cli = Boggle::Cli.new(
  board:      Boggle::build_board,
  speed:      1,
  duration:   2 * 60, # seconds
  start_time: Time.now,
)

# hide / show cursor
print cli.hide_cursor
at_exit { print cli.show_cursor }

# read chars instead of lines
$stdin.raw!
at_exit { $stdin.cooked! }

printer = Thread.new do
  until cli.over?
    $stdout.print cli.to_s $stdin.winsize
    sleep
  end
end

Thread.new do
  loop do
    chars = $stdin.readpartial(1000).chars
    printer.wakeup if chars.map { |c| cli.add_input c }.any?
  end
end

Thread.new do
  loop do
    sleep 1.0/cli.speed
    printer.wakeup if cli.update_time Time.now
  end
end

printer.join

print cli.final_screen $stdin.winsize
